---
- name: Create NFS Directory
  file:
    path: "{{ _nfs.root_dir }}"
    state: directory
    mode: "{{ _nfs.mode }}"


- name: Set SELinux NFS Share Policy
  shell: |
    setsebool -P {{ item }} 1
  register: set_selinux_nfs_share_policy
  with_items:
    - "nfs_export_all_rw"
    - "nfs_export_all_ro"
    - "use_nfs_home_dirs"


#- name: Config NFS SELinux Policy
#  shell: |
#    semanage fcontext -a -t {{ item.cont }}Â  "{{ _nfs.root_dir }}/{{ item.perm }}(/.*)?"
#  register: config_selinux
#  with_items:
#    - { cont: "public_content_rw_t", perm: "wasShare"}
#    - { cont: "public_content_t", perm: "readonly" }


- name: Restore SELinux Context
  shell: |
    restorecon -Rv {{ _nfs.root_dir }}
  register: restore_selinux_context


- name: Install NFS Server
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nfs-utils


- name: Export NFS Config
  lineinfile:
    path: /etc/exports
    line: "{{ item }}"
  with_items:
    - "/ovirt-nfs-root {{ nfs_network_range0 }}(rw,sync,no_subtree_check,no_root_squash)"
    - "/ovirt-nfs-root {{ nfs_network_range2 }}(rw,sync,no_subtree_check,no_root_squash)"


- name: Start NFS Server
  service:
    name: nfs-server
    state: started



- name: Enable NFS Ports for Firewalld
  firewalld:
    service: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  ignore_errors: true
  with_items:
    - nfs
    - mountd
    - rpc-bind

